export default {
  slug: "candlelight",
  title: "Candlelight Wiki",
  logo: "/assets/mod-logos/candlelight.png",
  aboutTitle: "Welcome",
  aboutSubtitle: "Fine dining, interiors, and a little bit of romance",
  aboutText: `
Welcome to the Candlelight Wiki.

This is your home for blocks, items, mechanics, and quick guidance for Candlelight.

Candlelight focuses on restaurant life in survival: furniture, decorative details, a writing and gifting theme, and a lineup of plated meals.

Alongside that, it introduces themed outfits, a lucky ring, and a few special showcase blocks that help your builds feel personal.
`,
  sections: [
    {
      id: "stations",
      title: "Stations and Processing",
      subtitle: "Workstations and interactive elements used for cooking and preparation.",
      entries: [
        {
          id: "stove",
          title: "Stove",
          namespace_id: "candlelight:*_stove",
          subtitle: "A heat source for cooking. Available in multiple stone variants.",
          icon: "/assets/icons/candlelight/cobblestone_stove.png",
          search: "stove heat cooking candlelight stone variants cobblestone sandstone stone bricks deepslate granite basalt quartz",
          details: true,
          detailsTitle: "Variants",
          detailsText: `Candlelight includes multiple Stove variants designed to match different stone palettes.

All variants share the same functionality.`,
          detailsBullets: [
            "Multiple stone themed designs",
            "Same functionality across all variants",
          ],
        },
        {
          id: "cooking_pot",
          title: "Cooking Pot",
          namespace_id: "candlelight:cooking_pot",
          subtitle: "A primary cooking station for Candlelight meals.",
          icon: "/assets/icons/candlelight/cooking_pot.png",
          search: "cooking pot station recipes meal candlelight",
          details: true,
          detailsTitle: "Usage",
          detailsText: `The Cooking Pot works similarly to other crafting stations.

It provides 6 ingredient slots, 1 container slot, and 1 output slot. It also includes a built in recipe book to browse available recipes.`,
          detailsBullets: [
            "6 ingredient slots",
            "1 container slot",
            "1 output slot",
            "Built in recipe book",
          ],
        },
        {
          id: "cooking_pan",
          title: "Cooking Pan",
          namespace_id: "candlelight:cooking_pan",
          subtitle: "A cooking pan that exists as a block and as an item.",
          icon: "/assets/icons/candlelight/cooking_pan.png",
          search: "cooking pan station block item candlelight",
          details: true,
          detailsTitle: "Overview",
          detailsText: `The Cooking Pan exists as a placed block and as an item.

The station works like the Cooking Pot and includes the same slot layout and recipe book.`,
          detailsBullets: [
            "Placed block variant",
            "Item variant",
            "Same workflow as the Cooking Pot",
          ],
        },
      ],
    },

    {
      id: "farming_utility",
      title: "Farming and Utility",
      subtitle: "Helpful everyday features and interactive utility blocks.",
      entries: [
        {
          id: "typewriter",
          title: "Typewriter",
          namespace_id: "candlelight:typewriter_iron",
          subtitle: "A writing block for longer letters. Available in Iron and Gold.",
          icon: "/assets/icons/candlelight/typewriter_iron.png",
          search: "typewriter writing letters note paper iron gold candlelight",
          details: true,
          detailsTitle: "Usage",
          detailsText: `Right click the Typewriter while holding Note Paper to insert it.

Right click again to open the interface. When finished, sign the letter and remove it with another right click.`,
          detailsBullets: [
            "Right click with Note Paper to insert",
            "Right click to open the interface",
            "Sign and remove the letter via interaction",
            "Iron and Gold variants",
          ],
          items: [
            {
              id: "typewriter_iron",
              title: "Iron Typewriter",
              namespace_id: "candlelight:typewriter_iron",
              subtitle: "",
              icon: "/assets/icons/candlelight/typewriter_iron.png",
              search: "typewriter iron",
            },
            {
              id: "typewriter_gold",
              title: "Gold Typewriter",
              namespace_id: "candlelight:typewriter_gold",
              subtitle: "",
              icon: "/assets/icons/candlelight/typewriter_gold.png",
              search: "typewriter gold",
            },
          ],
        },
        {
          id: "note_paper_and_letters",
          title: "Note Paper and Letter",
          namespace_id: "candlelight:note_paper_writeable",
          subtitle: "Write notes, seal letters, and exchange messages.",
          icon: "/assets/icons/candlelight/note_paper.png",
          search: "note paper letter love letter writable written sealed candlelight typewriter",
          details: true,
          detailsTitle: "Usage",
          detailsText: `You can write notes using Writable Note Paper or by using a Typewriter filled with Note Paper.

To seal a letter, combine a written note and an open envelope in the letter interface to create a closed letter.`,
          detailsBullets: [
            "Write notes using Writable Note Paper or the Typewriter",
            "Create closed letters through the letter interface",
            "Includes love letter variants",
          ],
          items: [
            {
              id: "note_paper",
              title: "Note Paper",
              namespace_id: "candlelight:note_paper",
              subtitle: "Paper used for writing and decoration.",
              icon: "/assets/icons/candlelight/note_paper.png",
              search: "note paper",
            },
            {
              id: "note_paper_writeable",
              title: "Writable Note Paper",
              namespace_id: "candlelight:note_paper_writeable",
              subtitle: "Write a note and sign it.",
              icon: "/assets/icons/candlelight/note_paper_writeable.png",
              search: "writable note paper",
            },
            {
              id: "note_paper_written",
              title: "Written Note Paper",
              namespace_id: "candlelight:note_paper_written",
              subtitle: "A finished written note.",
              icon: "/assets/icons/candlelight/note_paper_written.png",
              search: "written note paper",
            },
            {
              id: "letter_open",
              title: "Letter",
              namespace_id: "candlelight:letter_open",
              subtitle: "An open letter used for sealing.",
              icon: "/assets/icons/candlelight/letter_open.png",
              search: "letter open",
            },
            {
              id: "letter_closed",
              title: "Sealed Letter",
              namespace_id: "candlelight:letter_closed",
              subtitle: "A sealed letter item.",
              icon: "/assets/icons/candlelight/letter_closed.png",
              search: "sealed letter closed",
            },
            {
              id: "love_letter_open",
              title: "Love Letter",
              namespace_id: "candlelight:love_letter_open",
              subtitle: "An open love letter used for sealing.",
              icon: "/assets/icons/candlelight/love_letter_open.png",
              search: "love letter open",
            },
            {
              id: "love_letter",
              title: "Sealed Love Letter",
              namespace_id: "candlelight:love_letter",
              subtitle: "A sealed love letter item.",
              icon: "/assets/icons/candlelight/love_letter.png",
              search: "sealed love letter closed",
            },
          ],
        },
      ],
    },

    {
      id: "decor_building",
      title: "Decor and Building",
      subtitle: "Furniture and decorative blocks for restaurants, dining rooms, and interiors.",
      entries: [
        {
          id: "drawer",
          title: "Drawer",
          namespace_id: "candlelight:*_drawer",
          subtitle: "A storage drawer. Available in all wood variants.",
          icon: "/assets/icons/candlelight/oak_drawer.png",
          search: "drawer storage wood variants oak spruce birch jungle acacia dark oak mangrove cherry bamboo candlelight",
        },
        {
          id: "cabinet",
          title: "Cabinet",
          namespace_id: "candlelight:*_cabinet",
          subtitle: "A storage cabinet. Available in all wood variants.",
          icon: "/assets/icons/candlelight/oak_cabinet.png",
          search: "cabinet storage wood variants oak spruce birch jungle acacia dark oak mangrove cherry bamboo candlelight",
        },
        {
          id: "table",
          title: "Table",
          namespace_id: "candlelight:*_table",
          subtitle: "A dining table. Available in all wood variants.",
          icon: "/assets/icons/candlelight/oak_table.png",
          search: "table dining wood variants oak spruce birch jungle acacia dark oak mangrove cherry bamboo candlelight",
        },
        {
          id: "chair",
          title: "Chair",
          namespace_id: "candlelight:*_chair",
          subtitle: "A chair. Available in all wood variants.",
          icon: "/assets/icons/candlelight/oak_chair.png",
          search: "chair seating wood variants oak spruce birch jungle acacia dark oak mangrove cherry bamboo candlelight",
        },
        {
          id: "big_table",
          title: "Big Table",
          namespace_id: "candlelight:*_big_table",
          subtitle: "A large dining table. Available in all wood variants.",
          icon: "/assets/icons/candlelight/oak_big_table.png",
          search: "big table large dining wood variants oak spruce birch jungle acacia dark oak mangrove cherry bamboo candlelight",
        },
        {
          id: "kitchen_sink",
          title: "Kitchen Sink",
          namespace_id: "candlelight:*_kitchen_sink",
          subtitle: "A kitchen sink. Available in multiple stone variants.",
          icon: "/assets/icons/candlelight/cobblestone_kitchen_sink.png",
          search: "kitchen sink stone variants cobblestone sandstone stone bricks deepslate granite basalt quartz candlelight",
          details: true,
          detailsTitle: "Variants",
          detailsText: `Candlelight includes multiple Kitchen Sink variants designed to match different stone palettes.

All variants share the same functionality.`,
          detailsBullets: [
            "Multiple stone themed designs",
            "Same functionality across all variants",
          ],
        },
        {
          id: "table_set",
          title: "Table Set",
          namespace_id: "candlelight:table_set",
          subtitle: "Placeable dining pieces for plates, bowls, glasses, and cloches.",
          icon: "/assets/icons/candlelight/plate.png",
          search: "table set plate bowl glass wine glass napkin cloche candlelight",
          details: true,
          detailsTitle: "Placeables",
          detailsText: `The Table Set lets you place different dining pieces for table decoration.`,
          detailsBullets: [
            "Plate and Bowl",
            "Glass and Wine Glass",
            "Napkin",
            "Cloche",
          ],
          items: [
            { id: "plate", title: "Plate", namespace_id: "candlelight:plate", subtitle: "", icon: "/assets/icons/candlelight/plate.png", search: "plate table set" },
            { id: "bowl", title: "Bowl", namespace_id: "candlelight:bowl", subtitle: "", icon: "/assets/icons/candlelight/bowl.png", search: "bowl table set" },
            { id: "glass", title: "Glass", namespace_id: "candlelight:glass", subtitle: "", icon: "/assets/icons/candlelight/glass.png", search: "glass table set" },
            { id: "wine_glass", title: "Wine Glass", namespace_id: "candlelight:wine_glass", subtitle: "", icon: "/assets/icons/candlelight/wine_glass.png", search: "wine glass table set" },
            { id: "napkin", title: "Napkin", namespace_id: "candlelight:napkin", subtitle: "", icon: "/assets/icons/candlelight/napkin.png", search: "napkin table set" },
            { id: "cloche", title: "Cloche", namespace_id: "candlelight:cloche", subtitle: "", icon: "/assets/icons/candlelight/cloche.png", search: "cloche table set" },
          ],
        },
        {
          id: "lamp",
          title: "Lamp",
          namespace_id: "candlelight:lamp",
          subtitle: "A placeable lamp for interiors.",
          icon: "/assets/icons/candlelight/lamp.png",
          search: "lamp light candlelight",
        },
        {
          id: "side_table",
          title: "Side Table",
          namespace_id: "candlelight:side_table",
          subtitle: "A small table to place items like books, lamps, lanterns, and decorations.",
          icon: "/assets/icons/candlelight/side_table.png",
          search: "side table place items books lamp lantern candlelight",
        },
        {
          id: "sofa",
          title: "Sofa",
          namespace_id: "candlelight:sofa",
          subtitle: "A sofa for seating and interior layouts.",
          icon: "/assets/icons/candlelight/sofa.png",
          search: "sofa seating candlelight",
        },
        {
          id: "dinner_bell",
          title: "Dinner Bell",
          namespace_id: "candlelight:dinner_bell",
          subtitle: "A bell block you can ring with right click.",
          icon: "/assets/icons/candlelight/dinner_bell.png",
          search: "dinner bell ring right click candlelight",
        },
        {
          id: "hearth",
          title: "Hearth",
          namespace_id: "candlelight:hearth",
          subtitle: "A decorative block that can be placed on walls.",
          icon: "/assets/icons/candlelight/hearth.png",
          search: "hearth wall placeable candlelight",
        },
        {
          id: "table_sign",
          title: "Table Sign",
          namespace_id: "candlelight:table_sign",
          subtitle: "A placeable decorative sign for tables and counters.",
          icon: "/assets/icons/candlelight/table_sign.png",
          search: "table sign placeable decor candlelight",
        },
        {
          id: "small_painting",
          title: "Small Painting",
          namespace_id: "candlelight:painting",
          subtitle: "A painting with multiple motifs. Right click to cycle.",
          icon: "/assets/icons/candlelight/painting.png",
          search: "small painting motifs cycle right click candlelight",
          details: true,
          detailsTitle: "Motifs",
          detailsText: `The Small Painting can display different motifs.

Right click the placed painting to cycle through the available designs.`,
          detailsBullets: [
            "Multiple motifs",
            "Right click to change motif",
            "Tribute style decoration",
          ],
        },
        {
          id: "jewelry_box",
          title: "Jewelry Box",
          namespace_id: "candlelight:jewelry_box",
          subtitle: "Store and display rings.",
          icon: "/assets/icons/candlelight/jewelry_box.png",
          search: "jewelry box rings store display candlelight",
          details: true,
          detailsTitle: "Usage",
          detailsText: `Store and display rings inside the box.`,
          detailsBullets: [
            "Stores rings",
            "Designed for display",
          ],
        },
        {
          id: "chocolate_box",
          title: "Chocolate Box",
          namespace_id: "candlelight:chocolate_box",
          subtitle: "A placed box you can eat from multiple times.",
          icon: "/assets/icons/candlelight/chocolate_box.png",
          search: "chocolate box eat multiple times placed candlelight",
        },
        {
          id: "completionist_banner",
          title: "Completionist Banner",
          namespace_id: "candlelight:candlelight_banner",
          subtitle: "A reward banner for completing Candlelight foods.",
          icon: "/assets/icons/candlelight/banner.png",
          search: "completionist banner reward foods advancements tooltip candlelight",
          details: true,
          detailsTitle: "Reward",
          detailsText: `The Completionist Banner is awarded to players who have crafted all different Candlelight Foods.

To receive the respective advancements, you need all required items in your inventory at the same time.`,
          detailsBullets: [
            "Reward for crafting all Candlelight Foods",
            "Tracked through advancements",
            "Includes a special thank you tooltip",
          ],
        },
      ],
    },

    {
      id: "items_ingredients_tools",
      title: "Items, Ingredients, and Tools",
      subtitle: "Wearables, accessories, and everyday items used across Candlelight.",
      entries: [
        {
          id: "gold_ring",
          title: "Gold Ring",
          namespace_id: "candlelight:gold_ring",
          subtitle: "A wearable ring that grants +2 Luck.",
          icon: "/assets/icons/candlelight/gold_ring.png",
          search: "gold ring +2 luck accessory candlelight",
          details: true,
          detailsTitle: "Effect",
          detailsText: `The Gold Ring grants +2 Luck while worn.`,
          detailsBullets: ["Grants +2 Luck"],
        },
        {
          id: "chefs_attire",
          title: "Chef’s Attire",
          namespace_id: "",
          subtitle: "Cooking themed outfit pieces.",
          icon: "/assets/icons/candlelight/cooking_hat.png",
          search: "chef attire cooking hat chefs jacket chefs pants chefs boots candlelight",
          details: true,
          detailsTitle: "Included Pieces",
          detailsText: ``,
          items: [
            { id: "cooking_hat", title: "Cooking Hat", namespace_id: "candlelight:cooking_hat", subtitle: "", icon: "/assets/icons/candlelight/cooking_hat.png", search: "cooking hat" },
            { id: "chefs_jacket", title: "Chef's Jacket", namespace_id: "candlelight:chefs_jacket", subtitle: "", icon: "/assets/icons/candlelight/chefs_jacket.png", search: "chefs jacket" },
            { id: "chefs_pants", title: "Chef's Pants", namespace_id: "candlelight:chefs_pants", subtitle: "", icon: "/assets/icons/candlelight/chefs_pants.png", search: "chefs pants" },
            { id: "chefs_boots", title: "Chef's Boots", namespace_id: "candlelight:chefs_boots", subtitle: "", icon: "/assets/icons/candlelight/chefs_boots.png", search: "chefs boots" },
          ],
        },
        {
          id: "evening_wear",
          title: "Evening Wear",
          namespace_id: "",
          subtitle: "Formal outfit pieces.",
          icon: "/assets/icons/candlelight/dress.png",
          search: "evening wear flower crown dress shirt formal shirt trousers vest necktie candlelight",
          details: true,
          detailsTitle: "Included Pieces",
          detailsText: ``,
          items: [
            { id: "flower_crown", title: "Flower Crown", namespace_id: "candlelight:flower_crown", subtitle: "", icon: "/assets/icons/candlelight/flower_crown.png", search: "flower crown" },
            { id: "dress", title: "Dress", namespace_id: "candlelight:dress", subtitle: "", icon: "/assets/icons/candlelight/dress.png", search: "dress" },
            { id: "shirt", title: "Shirt", namespace_id: "candlelight:shirt", subtitle: "", icon: "/assets/icons/candlelight/shirt.png", search: "shirt" },
            { id: "formal_shirt", title: "Formal Shirt", namespace_id: "candlelight:formal_shirt", subtitle: "", icon: "/assets/icons/candlelight/formal_shirt.png", search: "formal shirt" },
            { id: "trousers_and_vest", title: "Trousers and Vest", namespace_id: "candlelight:trousers_and_vest", subtitle: "", icon: "/assets/icons/candlelight/trousers_and_vest.png", search: "trousers and vest" },
            { id: "necktie", title: "Necktie", namespace_id: "candlelight:necktie", subtitle: "", icon: "/assets/icons/candlelight/necktie.png", search: "necktie" },
          ],
        },
      ],
    },

    {
      id: "consumables",
      title: "Consumables",
      subtitle: "Meals, salads, soups, and other food items.",
      entries: [
        {
          id: "food",
          title: "Food",
          namespace_id: "",
          subtitle: "Prepared in the Cooking Pot or Cooking Pan. Many meals can be eaten multiple times.",
          icon: "/assets/icons/candlelight/lasagne.png",
          search: "candlelight food meals plated soups pasta steak salad",
          details: true,
          detailsTitle: "Notes",
          detailsText: `Most Candlelight food is prepared in the Cooking Pot or Cooking Pan.

If a meal is prepared using a potion or wine, it inherits the effect from the used drink.`,
          detailsBullets: [
            "Prepared in Cooking Pot or Cooking Pan",
            "Can inherit effects from used drinks",
            "Many meals can be eaten multiple times",
          ],
          items: [
            { id: "tomato_soup", title: "Tomato Soup", subtitle: "", icon: "/assets/icons/candlelight/tomato_soup.png", search: "tomato soup" },
            { id: "mushroom_soup", title: "Mushroom Soup", subtitle: "", icon: "/assets/icons/candlelight/mushroom_soup.png", search: "mushroom soup" },
            { id: "pasta_with_mozzarella", title: "Pasta With Mozzarella", subtitle: "", icon: "/assets/icons/candlelight/pasta_with_mozzarella.png", search: "pasta mozzarella" },
            { id: "bolognese", title: "Bolognese", subtitle: "", icon: "/assets/icons/candlelight/bolognese.png", search: "bolognese" },
            { id: "pasta_with_bolognese", title: "Pasta With Bolognese", subtitle: "", icon: "/assets/icons/candlelight/pasta_with_bolognese.png", search: "pasta bolognese" },
            { id: "beef_with_mushroom_in_wine_and_potatoes", title: "Beef With Mushroom In Wine And Potatoes", subtitle: "", icon: "/assets/icons/candlelight/beef_with_mushroom_in_wine_and_potatoes.png", search: "beef mushroom wine potatoes" },
            { id: "roastbeef_with_glazed_carrots", title: "Roastbeef With Glazed Carrots", subtitle: "", icon: "/assets/icons/candlelight/roastbeef_with_glazed_carrots.png", search: "roastbeef glazed carrots" },
            { id: "roasted_lamb_with_lettuce", title: "Roasted Lamb With Lettuce", subtitle: "", icon: "/assets/icons/candlelight/roasted_lamb_with_lettuce.png", search: "roasted lamb" },
            { id: "fillet_steak", title: "Fillet Steak", subtitle: "", icon: "/assets/icons/candlelight/fillet_steak.png", search: "fillet steak" },
            { id: "chicken_alfredo", title: "Chicken Alfredo", subtitle: "", icon: "/assets/icons/candlelight/chicken_alfredo.png", search: "chicken alfredo" },
            { id: "salmon_on_white_wine", title: "Salmon On White Wine", subtitle: "", icon: "/assets/icons/candlelight/salmon_on_white_wine.png", search: "salmon white wine" },
            { id: "chicken_with_vegetables", title: "Chicken With Vegetables", subtitle: "", icon: "/assets/icons/candlelight/chicken_with_vegetables.png", search: "chicken vegetables" },
            { id: "tropical_fish_supreme", title: "Tropical Fish Supreme", subtitle: "", icon: "/assets/icons/candlelight/tropical_fish_supreme.png", search: "tropical fish" },
            { id: "lasagne", title: "Lasagne", subtitle: "", icon: "/assets/icons/candlelight/lasagne.png", search: "lasagne" },
            { id: "beef_wellington", title: "Beef Wellington", subtitle: "", icon: "/assets/icons/candlelight/beef_wellington.png", search: "beef wellington" },
            { id: "pork_ribs", title: "Pork Ribs", subtitle: "", icon: "/assets/icons/candlelight/pork_ribs.png", search: "pork ribs" },
            { id: "fresh_garden_salad", title: "Fresh Garden Salad", subtitle: "", icon: "/assets/icons/candlelight/fresh_garden_salad.png", search: "fresh garden salad" },
            { id: "tomato_mozzarella_salad", title: "Tomato Mozzarella Salad", subtitle: "", icon: "/assets/icons/candlelight/tomato_mozzarella_salad.png", search: "tomato mozzarella salad" },
            { id: "salad", title: "Salad", subtitle: "", icon: "/assets/icons/candlelight/salad.png", search: "salad" },
            { id: "beetroot_salad", title: "Beetroot Salad", subtitle: "", icon: "/assets/icons/candlelight/beetroot_salad.png", search: "beetroot salad" },
            { id: "pasta_with_lettuce", title: "Pasta With Lettuce", subtitle: "", icon: "/assets/icons/candlelight/pasta_with_lettuce.png", search: "pasta" },
            { id: "khinkali", title: "Khinkali", subtitle: "", icon: "/assets/icons/candlelight/khinkali.png", search: "khinkali" },
            { id: "omelet", title: "Omelet", subtitle: "", icon: "/assets/icons/candlelight/omelet.png", search: "omelet" },
            { id: "harvest_plate", title: "Harvest Plate", subtitle: "", icon: "/assets/icons/candlelight/harvest_plate.png", search: "harvest plate" },
            { id: "chocolate_mousse", title: "Chocolate Mousse", subtitle: "", icon: "/assets/icons/candlelight/chocolate_mousse.png", search: "chocolate mousse" },
            { id: "beef_tartare", title: "Beef Tartare", subtitle: "", icon: "/assets/icons/candlelight/beef_tartare.png", search: "beef tartare" },
            { id: "chicken_teriyaki", title: "Chicken Teriyaki", subtitle: "", icon: "/assets/icons/candlelight/chicken_teriyaki.png", search: "chicken teriyaki" },
            { id: "mozzarella", title: "Mozzarella", subtitle: "", icon: "/assets/icons/candlelight/mozzarella.png", search: "mozzarella" },
          ],
        },
      ],
    },

    {
      id: "crops",
      title: "Crops and Wild Plants",
      subtitle: "Naturally generating plants found in newly generated chunks.",
      entries: [
        {
          id: "rose",
          title: "Rose",
          namespace_id: "candlelight:rose",
          subtitle: "Roses can generate naturally in specific biomes.",
          icon: "/assets/icons/candlelight/rose.png",
          search: "rose flower worldgen biomes forest plains swamp birch meadow sunflower plains river candlelight",
          details: true,
          detailsTitle: "Biomes",
          detailsText: `Roses can generate naturally in the following biomes.`,
          detailsBullets: [
            "minecraft:forest",
            "minecraft:plains",
            "minecraft:swamp",
            "minecraft:birch_forest",
            "minecraft:meadow",
            "minecraft:sunflower_plains",
            "minecraft:river",
          ],
        },
        {
          id: "potted_rose",
          title: "Potted Rose",
          namespace_id: "candlelight:potted_rose",
          subtitle: "A potted rose for shelves and tables.",
          icon: "/assets/icons/candlelight/potted_rose.png",
          search: "potted rose flower pot candlelight",
        },
      ],
    },

    {
      id: "misc_changes",
      title: "Miscellaneous Changes",
      subtitle: "Small tweaks and additions that enhance gameplay.",
      entries: [
        {
          id: "config",
          title: "Configuration",
          subtitle: "Most gameplay features of Candlelight can be adjusted via a configuration file, usually located at `config/candlelight.json`.",
          icon: "/assets/icons/misc/config.png",
          search: "config configuration settings options json candlelight",
        },
{
  id: "chef_zombies",
  title: "Chef Zombies",
  subtitle: "Sometimes zombies spawn wearing a cooking hat.",
  icon: "/assets/icons/misc/zombie.png",
  search: "chef zombie candlelight cooking hat spawn",
},
      ],
    },
  ],
};